{{-- select2 script --}}
<script src="{{ asset('plugin/cms/bower_components/select2/js/select2.full.min.js') }}"></script>
<script src="{{ asset('plugin/cms/bower_components/bootstrap-multiselect/js/bootstrap-multiselect.js') }}"></script>
<script src="{{ asset('plugin/cms/bower_components/multiselect/js/jquery.multi-select.js') }}"></script>
<script src="{{ asset('plugin/cms/assets/js/jquery.quicksearch.js') }}"></script>
<script src="{{ asset('plugin/cms/assets/pages/advance-elements/select2-custom.js') }}"></script>
{{-- datepicker script --}}
<script src="{{ asset('plugin/cms/assets/pages/advance-elements/moment-with-locales.min.js') }}"></script>
<script src="{{ asset('plugin/cms/bower_components/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('plugin/cms/assets/pages/advance-elements/bootstrap-datetimepicker.min.js') }}"></script>
<script src="{{ asset('plugin/cms/bower_components/bootstrap-daterangepicker/js/daterangepicker.js') }}"></script>
<script src="{{ asset('plugin/cms/bower_components/datedropper/js/datedropper.min.js') }}"></script>
<script src="{{ asset('plugin/cms/bower_components/spectrum/js/spectrum.js') }}"></script>
<script src="{{ asset('plugin/cms/bower_components/jscolor/js/jscolor.js') }}"></script>
<script src="{{ asset('plugin/cms/bower_components/jquery-minicolors/js/jquery.minicolors.min.js') }}"></script>
<script src="{{ asset('plugin/cms/assets/pages/advance-elements/custom-picker.js') }}"></script>
<script src="{{ asset('plugin/cms/assets/js/moment-with-locales.min.js') }}"></script>
