@startuml
skinparam titleBackgroundColor Aqua-CadetBlue
skinparam TitleFontSize 14
title **Activity when customer order food**\n

start
:Hello world;
:This is defined on
several **lines**;
stop
@enduml